### ISSUE TITLE
Build fails without docbook-xsl

### ISSUE THREAD

**Issue by usedbytes** [systemd/systemd-bootchart#24]
Building on Arch from https://aur.archlinux.org/packages/systemd-bootchart-git fails if `docbook-xsl` isn't installed. I guess it should be somehow flagged as a build dependency?

```
/usr/bin/xsltproc -o man/bootchart.conf.5 --nonet --xinclude --stringparam man.output.quietly 1 --stringparam funcsynopsis.style ansi --stringparam man.authors.section.enabled 0 --stringparam man.copyright.section.enabled 0 --stringparam systemd.version 231 --path './man:./man' ./man/custom-man.xsl man/bootchart.conf.xml
I/O error : Attempt to load network entity http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl"
compilation error: file ./man/custom-man.xsl line 27 element import
xsl:import : unable to load http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
make[2]: *** [Makefile:1765: man/bootchart.conf.5] Error 5
make[1]: *** [Makefile:1309: all-recursive] Error 1
make: *** [Makefile:648: all] Error 2
```

Found a similar issue here with a fix: https://github.com/hughsie/appdata-tools/issues/10

**Comment by ycongal-smile** [comment]
FYI, the URL with the fix has been removed but is [available on archive.org](https://web.archive.org/web/20141222170558/https://github.com/hughsie/appdata-tools/issues/10).

The gist of the fix is to install `docbook-xsl` or equivalent (works on my debian 10.1)

**Comment by treedavies** [comment]
Can the need for docbook be disabled from the build?
